[build]
  command = "npm run deploy"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# No Next.js runtime plugin needed for static export
