[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

# Configuration Netlify Forms
[[headers]]
  for = "/contact"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Configuration pour l'envoi d'emails (sera configuré dans l'interface Netlify)
# Dans l'interface Netlify : Settings > Forms > Form notifications > Add notification > Email
# Email: stephmyej+FormulaireContactSiteWeb@gmail.com
